# Generated by Django 5.0.3 on 2024-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_exercises_description_alter_exercises_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercises",
            name="muscle_group",
            field=models.CharField(
                choices=[
                    ("LB", "Lower Body"),
                    ("UB", "Upper Body"),
                    ("FB", "Full Body"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exercises",
            name="muscle_subrgoup",
            field=models.CharField(choices=[("CH", "Chest")], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="exercises",
            name="type",
            field=models.CharField(
                choices=[("LW", "Lift Weights"), ("LT", "Lift Time"), ("C", "Cardio")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exercises",
            name="description",
            field=models.TextField(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="exercises",
            name="link",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
